apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-ng-1
  labels:
    app: kub-ng-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub-ng-1
  template:
    metadata:
      labels:
        app: kub-ng-1
    spec:
      containers:
        - name: kub-ng-1
          image: kub-ng-1-nginx:latest
          imagePullPolicy: Never # use the image you build inside Minikube's Docker daemon
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kub-ng-1
  labels:
    app: kub-ng-1
spec:
  type: NodePort
  selector:
    app: kub-ng-1
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
